name: Mi Primer Action

on: [push, pull_request]

jobs:
  # Invocación del workflow reutilizable como si fuera una función
  preparar_entorno_job:
    uses: ./.github/workflows/setup-node-reusable.yml
    with:
      node-version: "20"
