name: Mi Primer Action

# El evento que dispara (trigger) el workflow
on: [push]

jobs:
  # Nombre del trabajo
  saludar_job:
    # El "Runner" (el sistema operativo de la PC en la nube)
    runs-on: ubuntu-latest

    # Las instrucciones secuenciales
    steps:
      - name: Imprimir saludo en la consola
        run: echo "¡Hola desde mi primer Action!"

  preparar_entorno_job:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Traer el código de tu repositorio al Runner
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      # Paso 2: Instalar y configurar Node.js en la máquina
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Es una buena práctica fijar la versión de tu entorno

      # Paso 3: Ejecutar comandos nativos de tu stack
      - name: Instalar dependencias
        run: npm install
